apiVersion: v2
name: streaming-platform
description: Helm chart for Streaming Platform (Frontend + Backend API + Encoder)
type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
    condition: backend.enabled

  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
    condition: frontend.enabled

  - name: monitoring
    version: 0.1.0
    repository: "file://charts/monitoring"
    condition: monitoring.enabled
