{
 "title": "Node.js Exporter",
 "description": "A quickstart to setup the Prometheus Node.js Exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "tags": [
  "node.js",
  "nodejs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(nodejs_eventloop_lag_seconds, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nodejs_eventloop_lag_seconds, instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "System CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m]) * 100",
     "legendFormat": "Total CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "graph",
   "description": "CPU time spent.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of active handle and active requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(http_active_conn)", "legendFormat": "Active Handler - {{instance}}" }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "graph",
   "description": "Latency of the event loop.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Last - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P99 - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P50 - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Resident - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External - {{instance}}"
    }
   ]
  }
 ]
}