{
 "title": "HAProxy",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_up{job=\"external-proxy\"},instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_up{instance=\"$host\"},backend)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_up{instance=\"$host\"},frontend)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_up{instance=\"$host\"},server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_frontend_http_responses_total,code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP response / request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Front {{ code }}"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Back {{ code }}"
    },
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front requests"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back requests"
    }
   ]
  },
  {
   "title": "Front - Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Front"
    }
   ]
  },
  {
   "title": "Back - Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  { "title": "Requests / Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Front - HTTP requests Total / Error / Denied",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Total {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Error {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Denied {{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - HTTP requests Total / Denied",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_requests_total{backend=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Total {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_requests_denied_total{backend=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Denied {{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - HTTP responses",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (proxy)",
     "legendFormat": "{{ proxy }} "
    }
   ]
  },
  {
   "title": "Back - HTTP responses",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])) by (proxy)",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - HTTP responses code",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ proxy }} "
    }
   ]
  },
  {
   "title": "Back - HTTP responses code",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ code }} {{ proxy }}"
    }
   ]
  },
  {
   "title": "Front - HTTP responses denied",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - HTTP responses denied",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_responses_denied_total{backend=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Back - Error / Redispatch / Retry",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Redispatch {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Retry {{ proxy }}"
    },
    {
     "expr": "rate(haproxy_backend_response_errors_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "Error {{ proxy }}"
    }
   ]
  }
 ]
}